sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
      - avishayalon@gmail.com
env:
  matrix:
    #- ROS_DISTRO="dashing"
    - ROS_DISTRO="eloquent" # ROS_REPO=testing
    #- ROS_DISTRO="dashing" ROS_REPOSITORY_PATH="http://packages.ros.org/ros2-testing/ubuntu" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
    #- ROS_DISTRO="dashing" ROS_REPOSITORY_PATH="http://repo.ros2.org/ubuntu/building" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
    - ROS_DISTRO="eloquent" ROS_REPOSITORY_PATH="http://packages.ros.org/ros2-testing/ubuntu" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
  global:
    - GH_USER_NAME="travis-ci"
    - GH_USER_EMAIL="travis@travis-ci.org"
    - AWS_DEFAULT_REGION=us-west-2
install:
  - git clone https://github.com/aws-robotics/utils-common
  - git clone https://github.com/aws-robotics/utils-ros2
  - git clone -b master https://github.com/ros-industrial/industrial_ci .ros_ci
script:
  - sed -i 's/"dashing")/"dashing"|"eloquent")/g' .ros_ci/industrial_ci/src/env.sh
  #- set +e; while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - .ros_ci/travis.sh
  #- kill %1
