sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
      - avishayalon@gmail.com
env:
  matrix:
    - ROS_DISTRO="dashing" ROS_REPO=testing
    - ROS_DISTRO="dashing" ROS_REPOSITORY_PATH="http://packages.ros.org/ros2-testing/ubuntu" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
    - ROS_DISTRO="dashing" ROS_REPO=building
    - ROS_DISTRO="dashing" ROS_REPOSITORY_PATH="http://repo.ros2.org/ubuntu/building" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
install:
  - git clone -b release-latest https://github.com/aws-robotics/kinesisvideo-encoder-ros2 kinesisvideo-encoder-ros2
  - git clone -b master https://github.com/ros-industrial/industrial_ci .ros_ci
script:
  - .ros_ci/travis.sh
