sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
      - avishayalon@gmail.com
env:
  matrix:
    - ROS_DISTRO="dashing" ROS_REPO=testing
    #- ROS_DISTRO="eloquent" ROS_REPO=testing
    - ROS_DISTRO="dashing" ROS_REPOSITORY_PATH="http://packages.ros.org/ros2-testing/ubuntu" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
    #- ROS_DISTRO="dashing" ROS_REPOSITORY_PATH="http://repo.ros2.org/ubuntu/building" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
    #- ROS_DISTRO="eloquent" ROS_REPOSITORY_PATH="http://packages.ros.org/ros2-testing/ubuntu" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
  global:
    - SA_NAME=hello-world
    - SA_PACKAGE_NAME=hello_world_robot
    - NO_TEST=true
    - GH_USER_NAME="travis-ci"
    - GH_USER_EMAIL="travis@travis-ci.org"
    - AWS_DEFAULT_REGION=us-west-2
install:
  - git clone -b ros2 https://github.com/aws-robotics/aws-robomaker-sample-application-helloworld vi_app
  #- mv vi_app/robot_ws vi_robot_ws && rm -rf vi_app
  #- rm vi_robot_ws/.rosinstall  
  - rm -rf vi_app/simulation_ws
  - git clone -b master https://github.com/ros-industrial/industrial_ci .ros_ci
script:
  #- sed -i 's/"dashing")/"dashing"|"eloquent")/g' .ros_ci/industrial_ci/src/env.sh
  - . .ros_ci/add_tag.sh
  - set +e; while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - sleep 10
  - kill %1
before_deploy:
- echo "Before deploy"
deploy:
  - provider: script
    script: echo "Deploy step"
    on:
      branch: master
after_deploy:
- echo "After deploy"
- exit 0
