sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
      - avishayalon@gmail.com
env:
  matrix:
    - ROS_DISTRO="dashing" ROS_REPO=testing
    - ROS_DISTRO="dashing" ROS_REPOSITORY_PATH="http://packages.ros.org/ros2-testing/ubuntu" PRERELEASE=true ABORT_ON_TEST_FAILURE=1
install:
  - git clone https://github.com/AAlon/utils-ros2.git utils-ros2
  - git clone https://github.com/AAlon/kinesisvideo-common.git kinesisvideo-common
  - git clone https://github.com/AAlon/kinesisvideo-encoder-common.git kinesisvideo-encoder-common
  - git clone https://github.com/AAlon/kinesisvideo-ros2.git kinesisvideo-ros2
  - git clone https://github.com/aws-robotics/cloudwatch-common cloudwatch-common
  - git clone https://github.com/aws-robotics/monitoringmessages-ros2 monitoringmessages-ros2
  - git clone https://github.com/aws-robotics/lex-common lex-common
  - git clone https://github.com/aws-robotics/lex-ros2 lex-ros2
  - git clone https://github.com/aws-robotics/tts-ros2 tts-ros2
  - git clone -b fix-build https://github.com/aws-robotics/kinesisvideo-encoder-ros2.git kinesisvideo-encoder-ros2
  - git clone -b fix-build https://github.com/aws-robotics/health-metrics-collector-ros2 health-metrics-collector-ros2
  - git clone -b fix-build https://github.com/aws-robotics/cloudwatchlogs-ros2 cloudwatchlogs-ros2
  - git clone -b fix-build https://github.com/aws-robotics/cloudwatchmetrics-ros2 cloudwatchmetrics-ros2
  - git clone -b master https://github.com/ros-industrial/industrial_ci .ros_ci
script:
  - .ros_ci/travis.sh
